// servicesData.js

function toWa(phone){
  const digits = String(phone || "").replace(/\D/g, "");
  if (!digits) return "";
  if (digits.startsWith("01")) return "6" + digits;
  if (digits.startsWith("601")) return digits;
  if (digits.startsWith("1")) return "60" + digits;
  return "";
}

function ASSET_BASE(){
  const p = String(location.pathname || "").replaceAll("\\", "/");
  return p.includes("/ServiceHub/") ? "../assets/" : "assets/";
}

function asset(fileName){
  return encodeURI(ASSET_BASE() + String(fileName || ""));
}

window.SERVICE_DATA = [
  {
    id: "car-gw-carrental",
    name: "Kereta Sewa Batu Pahat (GW Carrental)",
    category: "Car Booking / Transport",
    area: "Batu Pahat",
    address: "4, Jln Zabedah, Kampung Pegawai, 83000 Batu Pahat, Johor",
    phone: "017-360 0531",
    whatsapp: toWa("017-360 0531"),
    price: "RM120–RM220 / day",
    tags: ["Car rental"],
    image: asset("KeretaSewaBatuPahatGWCarrental.webp"),
    description: "Kereta sewa untuk sekitar Batu Pahat.",
    mapsQuery: "Kereta Sewa Batu Pahat (GW Carrental), 4, Jln Zabedah, Kampung Pegawai, 83000 Batu Pahat, Johor"
  },
  {
    id: "laundry-bubblelab",
    name: "Dobi Bubblelab Batu Pahat (Self-service laundry)",
    category: "Laundry & Ironing",
    area: "Batu Pahat",
    address: "42a, Jalan Chengal, Taman Batu Pahat, 83000 Batu Pahat, Johor",
    phone: "",
    whatsapp: "",
    price: "RM8–RM22 / wash",
    tags: ["Self-service"],
    image: asset("DobiBubblelabBatuPahatSelfservicelaundry.webp"),
    description: "Dobi layan diri sekitar Batu Pahat.",
    mapsQuery: "Dobi Bubblelab Batu Pahat, 42a, Jalan Chengal, Taman Batu Pahat, 83000 Batu Pahat, Johor"
  },
  {
    id: "laundry-de-dobi-parit-raja",
    name: "De Dobi Parit Raja Outlet",
    category: "Laundry & Ironing",
    area: "Parit Raja",
    address: "5, Jalan Gemilang Harmoni, Taman Gemilang Harmoni, 86400 Parit Raja, Johor",
    phone: "",
    whatsapp: "",
    price: "RM10–RM28 / wash",
    tags: ["Laundry"],
    image: asset("DeDobiParitRajaOutlet.webp"),
    description: "Dobi sekitar Parit Raja.",
    mapsQuery: "De Dobi Parit Raja Outlet, 5, Jalan Gemilang Harmoni, Taman Gemilang Harmoni, 86400 Parit Raja, Johor"
  },
  {
    id: "laundry-laundrybar-sri-gading",
    name: "Kedai Dobi Layan Diri Laundrybar",
    category: "Laundry & Ironing",
    area: "Sri Gading",
    address: "Jalan Kencana 1a/21, Sri Gading, 83300 Sri Gading, Johor Darul Ta'zim",
    phone: "019-488 8621",
    whatsapp: toWa("019-488 8621"),
    price: "RM8–RM20 / wash",
    tags: ["Self-service"],
    image: asset("KedaiDobiLayanDiriLaundrybar.jpg"),
    description: "Dobi layan diri di kawasan Sri Gading.",
    mapsQuery: "Kedai Dobi Layan Diri Laundrybar, Jalan Kencana 1a/21, Sri Gading, 83300 Sri Gading, Johor"
  },
  {
    id: "laundry-cleanpro-batu-pahat",
    name: "Cleanpro Express Self Service Laundry | Batu Pahat",
    category: "Laundry & Ironing",
    area: "Batu Pahat",
    address: "143, Jalan Rugayah, Kim's Park Business Centre, 83000 Batu Pahat, Johor",
    phone: "03-2770 0100",
    whatsapp: toWa("03-2770 0100"),
    price: "RM9–RM24 / wash",
    tags: ["Self-service"],
    image: asset("CleanproExpressSelfServiceLaundryBatuPahat.webp"),
    description: "Dobi layan diri (chain).",
    mapsQuery: "Cleanpro Express Self Service Laundry Batu Pahat, 143, Jalan Rugayah, Kim's Park Business Centre, 83000 Batu Pahat, Johor"
  },
  {
    id: "laundry-ruhban",
    name: "Ruhban Laundry",
    category: "Laundry & Ironing",
    area: "Batu Pahat",
    address: "58, Jalan Abdul Ghaffar, Kampung Merdeka, 83000 Batu Pahat, Johor Darul Ta'zim",
    phone: "",
    whatsapp: "",
    price: "RM12–RM45 / service",
    tags: ["Laundry"],
    image: asset("RuhbanLaundry.jpg"),
    description: "Servis dobi di Kampung Merdeka.",
    mapsQuery: "Ruhban Laundry, 58, Jalan Abdul Ghaffar, Kampung Merdeka, 83000 Batu Pahat, Johor"
  },
  {
    id: "transport-airport-coach-bus",
    name: "Airport Coach Bus",
    category: "Car Booking / Transport",
    area: "Batu Pahat",
    address: "Jalan Abu Bakar, Kampung Pegawai, 83000 Batu Pahat, Johor",
    phone: "010-222 2394",
    whatsapp: toWa("010-222 2394"),
    price: "RM18–RM55 / trip",
    tags: ["Bus", "Coach"],
    image: asset("AirportCoachBus.webp"),
    description: "Perkhidmatan bas/coach (rujuk operator untuk jadual).",
    mapsQuery: "Airport Coach Bus, Jalan Abu Bakar, Kampung Pegawai, 83000 Batu Pahat, Johor"
  },
  {
    id: "car-mr-yakin-enterprise",
    name: "Kereta sewa Batu Pahat (MR Yakin Enterprise)",
    category: "Car Booking / Transport",
    area: "Batu Pahat",
    address: "70, Jalan S/P 4, Taman Sri Panchor, 83300 Batu Pahat, Johor",
    phone: "016-355 6560",
    whatsapp: toWa("016-355 6560"),
    price: "RM110–RM210 / day",
    tags: ["Car rental"],
    image: asset("KeretasewaBatuPahatMRYakinEnterprise.webp"),
    description: "Kereta sewa sekitar Batu Pahat.",
    mapsQuery: "Kereta sewa Batu Pahat (MR Yakin Enterprise), 70, Jalan S/P 4, Taman Sri Panchor, 83300 Batu Pahat, Johor"
  },
  {
    id: "repair-iriza-tyre-car-service",
    name: "Irizas Tyre & Car Service Centre",
    category: "Repair & Maintenance",
    area: "Parit Raja",
    address: "2.2A Jalan Universiti 3, Taman Universiti Parit Raja, 86400 Batu Pahat, Johor",
    phone: "07-453 5006",
    whatsapp: toWa("07-453 5006"),
    price: "RM30–RM250 / service",
    tags: ["Tyre", "Car service"],
    image: asset("IrizasTyreCarServiceCentre.webp"),
    description: "Servis tayar & kereta di Parit Raja.",
    mapsQuery: "Irizas Tyre & Car Service Centre, 2.2A Jalan Universiti 3, Taman Universiti, 86400 Parit Raja, Johor"
  },
  {
    id: "delivery-post-centre-collectco-ersyah",
    name: "Post Centre BP (CollectCo) (Ersyah Enterprise)",
    category: "Moving / Delivery",
    area: "Parit Raja",
    address: "9, Jalan Universiti 2, Taman Universiti, 86400 Parit Raja, Johor",
    phone: "",
    whatsapp: "",
    price: "RM5–RM25 / parcel",
    tags: ["Drop off", "Courier"],
    image: asset("PostCentreBPCollectCoErsyahEnterprise.webp"),
    description: "Pusat drop-off courier (rujuk kaunter untuk servis yang tersedia).",
    mapsQuery: "Post Centre BP CollectCo Ersyah Enterprise, 9, Jalan Universiti 2, Taman Universiti, 86400 Parit Raja, Johor"
  },
  {
    id: "car-nadim-car-rental",
    name: "Kereta Sewa Batu Pahat (Nadim Car Rental)",
    category: "Car Booking / Transport",
    area: "Batu Pahat",
    address: "2237A, Jalan Talib Abu, Kampung Sateh, 83000 Batu Pahat, Johor",
    phone: "011-7312 4040",
    whatsapp: toWa("011-7312 4040"),
    price: "RM130–RM240 / day",
    tags: ["Car rental"],
    image: asset("KeretaSewaBatuPahatNadimCarRental.jpg"),
    description: "Kereta sewa sekitar Batu Pahat.",
    mapsQuery: "Kereta Sewa Batu Pahat (Nadim Car Rental), 2237A, Jalan Talib Abu, Kampung Sateh, 83000 Batu Pahat, Johor"
  },
  {
    id: "food-dzan-catering",
    name: "Dzan Catering Batu Pahat",
    category: "Food & Catering",
    area: "Batu Pahat",
    address: "Lot 2236, lorong haji awang Kampung bintang, mukim 3, 83000 Batu Pahat, Johor Darul Ta'zim",
    phone: "016-703 4411",
    whatsapp: toWa("016-703 4411"),
    price: "RM180–RM650 / event",
    tags: ["Catering"],
    image: asset("DzanCateringBatuPahat.webp"),
    description: "Catering untuk majlis & acara (ikut tempahan).",
    mapsQuery: "Dzan Catering Batu Pahat, Lot 2236, lorong haji awang Kampung bintang, mukim 3, 83000 Batu Pahat, Johor"
  },
  {
    id: "food-deawana-catering-canopy",
    name: "DeAWANA CATERING & CANOPY",
    category: "Food & Catering",
    area: "Parit Raja",
    address: "7, Jalan Universiti 1, Taman universiti, 86400 Parit Raja, Johor",
    phone: "012-792 9654",
    whatsapp: toWa("012-792 9654"),
    price: "RM220–RM900 / event",
    tags: ["Catering", "Canopy"],
    image: asset("DeAWANACATERINGCANOPY.webp"),
    description: "Catering & canopy untuk event.",
    mapsQuery: "DeAWANA CATERING & CANOPY, 7, Jalan Universiti 1, Taman Universiti, 86400 Parit Raja, Johor"
  },
  {
    id: "food-bake-with-yen-bp",
    name: "Bake With Yen Batu Pahat",
    category: "Food & Catering",
    area: "Batu Pahat",
    address: "No 10 & 11, Jalan Kundang, Taman Bukit Pasir, 83000 Batu Pahat, Johor",
    phone: "07-431 4555",
    whatsapp: toWa("07-431 4555"),
    price: "RM10–RM120 / item",
    tags: ["Baking supply"],
    image: asset("BakeWitYenBatuPahat.webp"),
    description: "Kedai bahan baking.",
    mapsQuery: "Bake With Yen Batu Pahat, No 10 & 11, Jalan Kundang, Taman Bukit Pasir, 83000 Batu Pahat, Johor"
  },
  {
    id: "food-dhoney-bakery-parit-raja",
    name: "D'Honey Bakery Parit Raja",
    category: "Food & Catering",
    area: "Parit Raja",
    address: "10, Jalan Kristal 5, Taman Kristal, 86400 Parit Raja, Johor",
    phone: "013-783 6210",
    whatsapp: toWa("013-783 6210"),
    price: "RM25–RM160 / order",
    tags: ["Bakery", "Cakes"],
    image: asset("DHoneyBakeryParitRaja.webp"),
    description: "Bakery (kek, dessert, roti).",
    mapsQuery: "D'Honey Bakery Parit Raja, 10, Jalan Kristal 5, Taman Kristal, 86400 Parit Raja, Johor"
  },
  {
    id: "printing-ilham-smart-printing",
    name: "Ilham Smart Printing",
    category: "Printing & Stationery",
    area: "Parit Raja",
    address: "8, Jalan Kristal 6, Taman Kristal, 86400 Parit Raja, Johor",
    phone: "07-457 0153",
    whatsapp: toWa("07-457 0153"),
    price: "RM0.30–RM1.50 / page",
    tags: ["Photocopy", "Printing"],
    image: asset("IlhamSmartPrinting.webp"),
    description: "Photocopy, printing, dan servis berkaitan.",
    mapsQuery: "Ilham Smart Printing, 8, Jalan Kristal 6, Taman Kristal, 86400 Parit Raja, Johor"
  },
  {
    id: "transport-rtd-batu-pahat-branch",
    name: "Road Transport Department (RTD), Batu Pahat Branch",
    category: "Car Booking / Transport",
    area: "Sri Gading",
    address: "KM 11, Jln Kluang, Sri Gading, 83300 Batu Pahat, Johor",
    phone: "",
    whatsapp: "",
    price: "Fees vary (official rates)",
    tags: ["JPJ", "Government"],
    image: asset("RoadTransportDepartmentRTDBatuPahatBranch.jpg"),
    description: "Cawangan JPJ Batu Pahat (rujuk waktu operasi rasmi).",
    mapsQuery: "Road Transport Department (RTD), Batu Pahat Branch, KM 11, Jln Kluang, Sri Gading, 83300 Batu Pahat, Johor"
  },
  {
    id: "printing-top-photocopy-centre",
    name: "Top Photocopy Centre",
    category: "Printing & Stationery",
    area: "Parit Raja",
    address: "2, Jalan Aked Utama, Taman Aked, 86400 Parit Raja, Johor",
    phone: "07-453 1267",
    whatsapp: toWa("07-453 1267"),
    price: "RM0.20–RM1.20 / page",
    tags: ["Photocopy"],
    image: asset("TopPhotocopyCentre.jpg"),
    description: "Photocopy & printing.",
    mapsQuery: "Top Photocopy Centre, 2, Jalan Aked Utama, Taman Aked, 86400 Parit Raja, Johor"
  },
  {
    id: "printing-oriental-art-printing",
    name: "Oriental Art Printing Enterprise Sdn Bhd",
    category: "Printing & Stationery",
    area: "Sri Gading",
    address: "No.9, Jln Wawasan 16, Kawasan Perindustrian Sri Gading, 83300 Batu Pahat, Johor",
    phone: "07-455 8868",
    whatsapp: toWa("07-455 8868"),
    price: "RM50–RM600 / job",
    tags: ["Printing"],
    image: asset("OrientalArtPrintingEnterpriseSdnBhd.jpeg"),
    description: "Syarikat printing.",
    mapsQuery: "Oriental Art Printing Enterprise Sdn Bhd, No.9, Jln Wawasan 16, Kawasan Perindustrian Sri Gading, 83300 Batu Pahat, Johor"
  },
  {
    id: "stationery-songbai",
    name: "Songbai Stationary Trading",
    category: "Printing & Stationery",
    area: "Batu Pahat",
    address: "38, Jalan Dato Wan Idris, Kampung Merdeka, 83000 Batu Pahat, Johor",
    phone: "017-721 1968",
    whatsapp: toWa("017-721 1968"),
    price: "RM2–RM80 / item",
    tags: ["Stationery"],
    image: asset("SongbaiStationaryTrading.webp"),
    description: "Kedai alat tulis / stationery.",
    mapsQuery: "Songbai Stationary Trading, 38, Jalan Dato Wan Idris, Kampung Merdeka, 83000 Batu Pahat, Johor"
  },
  {
    id: "stationery-keong-stationeries",
    name: "Keong Stationeries Trading Sdn Bhd",
    category: "Printing & Stationery",
    area: "Batu Pahat",
    address: "No. 9, Jalan Kundang 4 (Wira Court), Taman Bukit Pasir, 83000 Batu Pahat, Johor",
    phone: "07-434 4494",
    whatsapp: toWa("07-434 4494"),
    price: "RM2–RM120 / item",
    tags: ["Stationery"],
    image: asset("KeongStationeriesTradingSdnBhd.webp"),
    description: "Kedai stationery.",
    mapsQuery: "Keong Stationeries Trading Sdn Bhd, No. 9, Jalan Kundang 4 (Wira Court), Taman Bukit Pasir, 83000 Batu Pahat, Johor"
  },
  {
    id: "repair-hitech-electronic-services",
    name: "Hitech Electronic Services",
    category: "Repair & Maintenance",
    area: "Batu Pahat",
    address: "NO. 88 & 88a, Jalan Cengal, Taman Makmur, 83000 Batu Pahat, Johor",
    phone: "07-431 6427",
    whatsapp: toWa("07-431 6427"),
    price: "RM35–RM250 / repair",
    tags: ["Electronics", "Repair"],
    image: asset("HitechElectronicServices.webp"),
    description: "Servis baik pulih elektronik.",
    mapsQuery: "Hitech Electronic Services, NO. 88 & 88a, Jalan Cengal, Taman Makmur, 83000 Batu Pahat, Johor"
  },
  {
    id: "repair-mr-budget-laptop-bp",
    name: "MR BUDGET LAPTOP Batu Pahat",
    category: "Repair & Maintenance",
    area: "Batu Pahat",
    address: "26, Jalan Flora Utama 4, Taman Flora Utama, 83000 Batu Pahat, Johor",
    phone: "011-5888 9050",
    whatsapp: toWa("011-5888 9050"),
    price: "RM50–RM280 / service",
    tags: ["Laptop", "Refurbished"],
    image: asset("MRBUDGETLAPTOPBatuPahat.webp"),
    description: "Laptop refurbished / servis berkaitan.",
    mapsQuery: "MR BUDGET LAPTOP Batu Pahat, 26, Jalan Flora Utama 4, Taman Flora Utama, 83000 Batu Pahat, Johor"
  },
  {
    id: "repair-xpertgadget-sri-gading",
    name: "XPERTGADGET SRI GADING - Mobile Phone Repair Specialist",
    category: "Repair & Maintenance",
    area: "Sri Gading",
    address: "9, Jalan Kencana 1a/1, Sri Gading, 83300 Sri Gading, Johor",
    phone: "019-978 8897",
    whatsapp: toWa("019-978 8897"),
    price: "RM30–RM220 / repair",
    tags: ["Phone repair"],
    image: asset("XPERTGADGETSRIGADINGMobilePhoneRepairSpecialist.webp"),
    description: "Servis repair telefon.",
    mapsQuery: "XPERTGADGET SRI GADING, 9, Jalan Kencana 1a/1, Sri Gading, 83300 Sri Gading, Johor"
  },
  {
    id: "repair-ayel-plumber",
    name: "Tukang Paip Batu Pahat | Ayel Plumber",
    category: "Repair & Maintenance",
    area: "Batu Pahat",
    address: "4, 86A Kg Pt Hj Salleh Batu, 1/2, Jln Kluang, 83000 Batu Pahat, Johor Darul Ta'zim",
    phone: "012-737 5795",
    whatsapp: toWa("012-737 5795"),
    price: "RM60–RM250 / visit",
    tags: ["Plumber"],
    image: asset("TukangPaipBatuPahatAyePlumber.jpg"),
    description: "Servis paip & plumbing.",
    mapsQuery: "Tukang Paip Batu Pahat Ayel Plumber, 4, 86A Kg Pt Hj Salleh, Jln Kluang, 83000 Batu Pahat, Johor"
  },
  {
    id: "repair-bengkel-kereta-alam-biru",
    name: "Bengkel Kereta Alam Biru",
    category: "Repair & Maintenance",
    area: "Parit Raja",
    address: "No. 13 A, Lorong Sri Hakim 1, Kampung Parit Haji Abdul Kadir, Parit Raja, 86400 Batu Pahat, Johor Darul Ta'zim",
    phone: "011-1078 0861",
    whatsapp: toWa("011-1078 0861"),
    price: "RM60–RM480 / service",
    tags: ["Workshop", "Car repair"],
    image: asset("BengkelKeretaAlamBiru.webp"),
    description: "Bengkel kereta & servis asas.",
    mapsQuery: "Bengkel Kereta Alam Biru, No. 13 A, Lorong Sri Hakim 1, Kampung Parit Haji Abdul Kadir, Parit Raja, 86400 Batu Pahat, Johor"
  },
  {
    id: "cleaning-hijau-bersih-bp",
    name: "Hijau Bersih Cleaning Services Batu Pahat",
    category: "Cleaning Services",
    area: "Batu Pahat",
    address: "Taman Flora Utama, 83000 Batu Pahat, Johor",
    phone: "018-223 4412",
    whatsapp: toWa("018-223 4412"),
    price: "RM90–RM350 / session",
    tags: ["House cleaning", "Office cleaning"],
    image: asset("HijauBersihCleaningServicesBatuPahat.webp"),
    description: "Perkhidmatan pembersihan rumah & pejabat sekitar Batu Pahat.",
    mapsQuery: "Hijau Bersih Cleaning Services Batu Pahat 83000"
  },
  {
    id: "delivery-fastgo-parit-raja",
    name: "FastGo Delivery Parit Raja",
    category: "Moving / Delivery",
    area: "Parit Raja",
    address: "Taman Universiti, 86400 Parit Raja, Johor",
    phone: "019-334 8891",
    whatsapp: toWa("019-334 8891"),
    price: "RM6–RM35 / delivery",
    tags: ["Delivery", "Runner"],
    image: asset("FastGoDeliveryParitRaja.jpeg"),
    description: "Servis runner & penghantaran sekitar Parit Raja dan Batu Pahat.",
    mapsQuery: "FastGo Delivery Parit Raja 86400"
  },
  {
    id: "tutor-smart-learning-bp",
    name: "Smart Learning Tuition Centre Batu Pahat",
    category: "Tutoring / Classes",
    area: "Batu Pahat",
    address: "Taman Bukit Pasir, 83000 Batu Pahat, Johor",
    phone: "017-778 2301",
    whatsapp: toWa("017-778 2301"),
    price: "RM80–RM220 / month",
    tags: ["Tuition", "SPM", "Math"],
    image: asset("SmartLearningTuitionCentreBatuPahat.jpg"),
    description: "Pusat tuisyen untuk pelajar sekolah menengah & rendah.",
    mapsQuery: "Smart Learning Tuition Centre Batu Pahat 83000"
  },
  {
    id: "moving-easy-move-bp",
    name: "EasyMove Transport & Moving Batu Pahat",
    category: "Moving / Delivery",
    area: "Batu Pahat",
    address: "Kampung Pegawai, 83000 Batu Pahat, Johor",
    phone: "012-998 5521",
    whatsapp: toWa("012-998 5521"),
    price: "RM120–RM650 / job",
    tags: ["Moving", "Lorry sewa"],
    image: asset("EasyMoveTransportMovingBatuPahat.jpg"),
    description: "Servis pindah rumah & sewaan lori sekitar Batu Pahat.",
    mapsQuery: "EasyMove Transport & Moving Batu Pahat 83000"
  }
];

window.SERVICE_CATEGORIES = [
  "All categories",
  "Cleaning Services",
  "Laundry & Ironing",
  "Car Booking / Transport",
  "Food & Catering",
  "Printing & Stationery",
  "Repair & Maintenance",
  "Tutoring / Classes",
  "Moving / Delivery"
];